LPS-152054
timpak/liferay-portal pull request #211
Opened 2022-05-16 19:21 UTC by evanilson-santana

2022-05-16 19:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-16 19:22 UTC, evanilson-santana commented
ci:test:sf

2022-05-16 19:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/2175/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2175/jenkins-report.html">here</a>.</b></p>

2022-05-16 19:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/648de36a734019adfafb1aa8525cf21a5afc5459">648de36a734019adfafb1aa8525cf21a5afc5459</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-152054">LPS-152054</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/c7dbe1c77e2e31ee84e3cdce5a66817d37e9faea">c7dbe1c77e2e31ee84e3cdce5a66817d37e9faea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2175/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2175/jenkins-report.html">here</a>.</h5></details></html>

2022-05-16 19:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2175/">test-portal-source-format#2175</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2175/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/211">timpak#211</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1850614793">[master] ci:test:sf - evanilson-santana &gt; timpak - PR#211 - 2022-05-16[12:22:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/8025/">publish-testray-report#8025</a><br/></div></div>

2022-05-17 09:22 UTC, timpak requested changes
@evanilson-santana looks good, just have a couple minor things to address. Can you rename the macro and squash your commits together? In the future, you can just add the SF changes to the original commit that caused the error.

2022-05-17 09:22 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectCustomViews.macro
> +	macro assertNoColumnAddYet {
Can you change this to assertNoColumnPresentInDefaultSort to make it clearer what we're asserting?

2022-05-18 07:30 UTC, timpak commented
See https://github.com/timpak/liferay-portal/pull/214#issuecomment-1129668804

2022-05-18 07:30 UTC, closed without merging