LPS-152059
timpak/liferay-portal pull request #213
Opened 2022-05-17 20:27 UTC by andreefarias

2022-05-17 20:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-17 20:28 UTC, andreefarias commented
ci:test:sf

2022-05-17 20:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/2612/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2612/jenkins-report.html">here</a>.</b></p>

2022-05-17 20:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47cb84a4a1472f8c51d35ecd753db4e08f88b1a8">47cb84a4a1472f8c51d35ecd753db4e08f88b1a8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-152059">LPS-152059</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/781caea67f7a21db62a5286abcb0b48b132a0fe2">781caea67f7a21db62a5286abcb0b48b132a0fe2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2612/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2612/jenkins-report.html">here</a>.</h5></details></html>

2022-05-17 20:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2612/">test-portal-source-format#2612</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2612/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/213">timpak#213</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1852102235">[master] ci:test:sf - andreefarias &gt; timpak - PR#213 - 2022-05-17[13:28:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/9708/">publish-testray-report#9708</a><br/></div></div>

2022-05-18 09:07 UTC, timpak requested changes
Hey @andreefarias, please see my comments below. You can send me another pull request once you make the necessary changes. Let me know if you need help or if something doesn't make sense!

2022-05-18 18:03 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomViews.testcase
> +			userLoginFullName = "userfn userln");
Hi, @timpak!

The role Power User don't check Objects proprieties by default. So, in some tests is necessary to mark the properties that will be use. If not, the user will not be able to make any changes relate Objects or Custom Objects.

2022-05-18 18:05 UTC, andreefarias commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomViews.testcase
> +			userLoginFullName = "userfn userln");
But, is possible change the creation Regular Role to Power User role.

2022-05-25 06:13 UTC, closed without merging

2022-05-25 07:15 UTC, timpak commented
See https://github.com/timpak/liferay-portal/pull/225

See my changes https://github.com/timpak/liferay-portal/pull/225/commits/395e605b2d457fde54310c1fae1551bf9f810f45 and https://github.com/timpak/liferay-portal/pull/225/commits/0bd60f969309f98fdb42972a829409104e40b0b5