LPS-157220
timpak/liferay-portal pull request #256
Opened 2022-06-29 17:07 UTC by andreefarias

2022-06-29 17:07 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-29 17:08 UTC, andreefarias commented
ci:test:sf

2022-06-29 17:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/1195/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1195/jenkins-report.html">here</a>.</b></p>

2022-06-29 17:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1195/">test-portal-source-format#1195</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1195/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/256">timpak#256</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1892360734">[master] ci:test:sf - andreefarias &gt; timpak - PR#256 - 2022-06-29[10:08:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/4690/">publish-testray-report#4690</a><br/></div></div>

2022-07-08 07:56 UTC, timpak requested changes

2022-07-08 07:56 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
>  			id = "",
From the test history, this is failing intermittently. The problem is that if the test is too fast, it'll navigate to the page in one second. If we apply the fix, it'll fail every time it takes longer than one second to nagivate to the page.

We should find a way for this to work 100% of the time. For example, you could try is adding a refresh after Audit.openAuditAdmin(); if it's the table contains "1 Second Ago".

2022-07-08 07:56 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectAudit.testcase
>  			id = "",
@andreefarias please find a method to make the test more resilient. You can try using the example above or find another method.

2022-07-08 07:56 UTC, closed without merging