LPS-156807
timpak/liferay-portal pull request #263
Opened 2022-07-08 18:13 UTC by andreefarias

2022-07-08 18:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-08 18:14 UTC, andreefarias commented
ci:test:sf

2022-07-08 18:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/2491/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/2491/jenkins-report.html">here</a>.</b></p>

2022-07-08 18:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03ececc28b5d2e6597bda4bf139bb6f67a8a5bef">03ececc28b5d2e6597bda4bf139bb6f67a8a5bef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-156807">LPS-156807</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/4171aa9082b83ba3814e528acc885c6d6bf97803">4171aa9082b83ba3814e528acc885c6d6bf97803</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/2491/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/2491/jenkins-report.html">here</a>.</h5></details></html>

2022-07-18 11:04 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomViews.testcase
> +
This looks like it was caught by SF? If you need to make SF changes to code that wasn't part of your changes, you can make them in a separate commit with the message "LPS-156807 Auto SF".

2022-07-18 11:06 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomViews.testcase
> -
It looks like you added the spaces in the previous commit and removed them here. Please remove them from the original commit next time using interactive rebase.

2022-07-18 11:10 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectCustomViews.macro
> +
Do we need to extract this into a macro? The code isn't being re-used and you're using tasks to explain what's happening in the test so I don't think we need to create this macro, unless I'm missing something. 

Out of curiosity, is the expected coding practice in Brazil to not use functions at the test case level?

2022-07-18 11:11 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomViews.testcase
> +
Similar to when we create the filter, we should use the filter on the object entries to make sure the changes are applied.

2022-07-18 11:11 UTC, timpak requested changes
@andreefarias please see my comments for required changes. You can send a new PR once you're done, I'm bringing my laptop with me so I'll be checking my review queue once a day.

2022-07-18 11:12 UTC, closed without merging