LPS-156663
timpak/liferay-portal pull request #299
Opened 2022-09-01 15:24 UTC by rafaellajordao

2022-09-01 15:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-01 15:30 UTC, rafaellajordao commented
ci:test:sf

2022-09-01 15:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2828/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2828/jenkins-report.html">here</a>.</b></p>

2022-09-01 15:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/258e854cf0a54b870f8a6afc8ff71fe04b5c62cd">258e854cf0a54b870f8a6afc8ff71fe04b5c62cd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LPS-156663">LPS-156663</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/6d498c3d210e416b2d36fe92c7848c6114a76680">6d498c3d210e416b2d36fe92c7848c6114a76680</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2828/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2828/jenkins-report.html">here</a>.</h5></details></html>

2022-09-05 11:47 UTC, timpak requested changes
Really great job with the tests @rafaellajordao!

One small request: `CanCreateManyToManyRelationshipWithNativeObject` can you expand the test to create an object entry and add the relationship using the UI? We're covering this scenario for One-to-Many in `CanDeleteOneToManyRelationship` but we aren't covering it for Many-to-Many. 

You can forward all of these tests once you add it. No need for me to review again. Thanks!

2022-09-05 11:47 UTC, closed without merging