LPS-156343, LPS-156327
timpak/liferay-portal pull request #305
Opened 2022-09-02 19:42 UTC by thaiscabrals

2022-09-02 19:42 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-02 19:43 UTC, thaiscabrals commented
ci:test:sf

2022-09-02 19:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4008/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4008/jenkins-report.html">here</a>.</b></p>

2022-09-02 19:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b9dc611e018829526a2c3957ac4bababc7798aa3">b9dc611e018829526a2c3957ac4bababc7798aa3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaiscabrals/liferay-portal/tree/LPS-156327">LPS-156327</a><br/>Branch GIT ID: <a href="https://github.com/thaiscabrals/liferay-portal/commit/65b899697ef459f2287330405284a363fb116ec0">65b899697ef459f2287330405284a363fb116ec0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4008/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4008/jenkins-report.html">here</a>.</h5></details></html>

2022-09-02 19:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4008/">test-portal-source-format#4008</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4008/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/305">timpak#305</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1965403083">[master] ci:test:sf - thaiscabrals &gt; timpak - PR#305 - 2022-09-02[12:43:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/14895/">publish-testray-report#14895</a><br/></div></div>

2022-09-05 12:12 UTC, timpak requested changes
Good job with the test! Please see my comment and resend.

Also, please squash all of these changes into one commit to keep the commit history clean. You shouldn't be making commits with spacing or SF errors and fixing them in separate commits.

2022-09-05 12:12 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
I think I remember seeing this in another PR from you. If you need these changes for this test as well, you should close the original PR, commit on top of it, then resend the PR.

2022-09-05 12:12 UTC, closed without merging

2022-09-05 22:51 UTC, evanilson-santana commented
New PR [here](https://github.com/timpak/liferay-portal/pull/309)