LPS-161917
timpak/liferay-portal pull request #322
Opened 2022-09-13 16:27 UTC by alanafergs

2022-09-13 16:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-13 16:28 UTC, alanafergs commented
ci:test:sf

2022-09-13 16:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/4750/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4750/jenkins-report.html">here</a>.</b></p>

2022-09-13 16:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4acfb3ed1e31069a4acea33367f5d5df63fb8549">4acfb3ed1e31069a4acea33367f5d5df63fb8549</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LPS-161917">LPS-161917</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/388f4367f53b8661c7210f67c92af89344b486af">388f4367f53b8661c7210f67c92af89344b486af</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4750/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4750/jenkins-report.html">here</a>.</h5></details></html>

2022-09-13 16:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4750/">test-portal-source-format#4750</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4750/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/322">timpak#322</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1975424239">[master] ci:test:sf - alanafergs &gt; timpak - PR#322 - 2022-09-13[09:29:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2210/">publish-testray-report#2210</a><br/></div></div>

2022-09-15 09:03 UTC, timpak requested changes
Congrats on your first Objects tests! Please see my comments for changes needed. Also, for SF changes, please make them in the commit that caused them instead of making a separate commit. In general, it's good practice to fix SF errors in the commit that caused them instead of fixing them in a separate commit.

Let me know if you need help with this!

2022-09-15 09:03 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/paths/ObjectNotifications.path
> +
We should have an appropriate path for the ellipsis in `Icon.path` and there's `MenuItem.path` for menu items.

2022-09-15 09:05 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectNotifications.testcase
> +     @description = "LPS-161918 - Verify that it's possible to edit an e-mail notification template"
Typo, should be `delete` instead of `edit`

2022-09-15 09:05 UTC, closed without merging