LPS-161897
timpak/liferay-portal pull request #345
Opened 2022-09-23 23:10 UTC by andreefarias

2022-09-23 23:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-09-23 23:10 UTC, andreefarias commented
ci:test:sf

2022-09-23 23:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/4185/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4185/jenkins-report.html">here</a>.</b></p>

2022-09-23 23:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e8dad1740ba70d388690eaebd4dc50e2e5cb624c">e8dad1740ba70d388690eaebd4dc50e2e5cb624c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-161897">LPS-161897</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/e4a3c912322f152e46f4766063fb562bd544f120">e4a3c912322f152e46f4766063fb562bd544f120</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4185/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4185/jenkins-report.html">here</a>.</h5></details></html>

2022-09-23 23:14 UTC, andreefarias commented
Hey @timpak, is correct the steps on testcase [CanRestrictExistingObject test](https://github.com/timpak/liferay-portal/pull/345/commits/e4a3c912322f152e46f4766063fb562bd544f120)? 

I described on tasks steps.

2022-09-23 23:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/4185/">test-portal-source-format#4185</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/4185/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/timpak/liferay-portal/pull/345">timpak#345</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1989790959">[master] ci:test:sf - andreefarias &gt; timpak - PR#345 - 2022-09-23[16:11:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/15585/">publish-testray-report#15585</a><br/></div></div>

2022-09-30 07:58 UTC, timpak requested changes
Hey @andreefarias, can you take a look at my comments below? Don't worry about the wording of the tasks for now, I'll change them later.

You can send the follow-up PR to the liferay-bpm-qa user and add the `Ready for Review` label

2022-09-30 07:58 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		}
Since we're adding two Objects via API with similar names, we can just use a loop here.

2022-09-30 07:58 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		task ("Add Relationship Account to Custom Object (via API)") {
I'll re-word this to make it more clear.

2022-09-30 07:58 UTC, timpak commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		}
Hey @andreefarias I think you flipped the scenario. You need to create the object, publish it, then activate account restriction.

2022-09-30 07:58 UTC, closed without merging